# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]
  # Triggers the workflow on push request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Running JUnit tests
        run: |
          echo Starting tests:
          mkdir bin
          mkdir lib
          curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.5.2/junit-platform-console-standalone-1.5.2.jar -o lib/junit-platform-console-standalone-1.5.2.jar
          javac -d bin/ $(find src/ -name "*.java")
          javac -d bin -cp bin:lib/junit-platform-console-standalone-1.5.2.jar $(find test/ -name "*.java")
          java -jar lib/junit-platform-console-standalone-1.5.2.jar --class-path bin --scan-class-path
